# Copyright (C) 2025 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

name: Enforce codespell-clean spelling

on:
  pull_request:
  push:
  schedule:
    - cron: '0 4 * * 5'  # Every Friday at 4am
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    name: Enforce codespell-clean spelling
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
    - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630  # v2.1
      with:
        # "inout" is from "<b>INOUT</b>" markers
        # "puls" is for last name "Puls" in files THANKS and ChangeLog
        # "worstcase" is from variable name "worstCase" in file src/UriQuery.c
        ignore_words_list: inout,puls,worstcase
        skip: ./doc/rfc1866.htm,./doc/rfc3513.htm,./doc/rfc3986.htm
